main: main.cpp
	echo ---------compiling main.cpp to create executable program main ----------
	g++ -ggdb -std=c++11 main.cpp -o main
	echo ---------removing executable program main ------------------------------
	/bin/rm main
